- .github/workflows/pre-commit.yml
> feat(ci): Add pre-commit check

- host/class/cdc/usb_host_cdc_acm/CHANGELOG.md
- host/class/cdc/usb_host_cdc_acm/cdc_acm_host.c
- host/class/cdc/usb_host_cdc_acm/include/usb/cdc_acm_host.h
- host/class/cdc/usb_host_cdc_acm/include/usb/usb_types_cdc.h
- host/class/cdc/usb_host_cdc_acm/test/test_cdc_acm_host.c
Added `cdc_acm_host_cdc_desc_get()` function with which users can requres CDC functional descriptor.
Tests included
> feat(cdc): Add API for getting CDC functional descriptors

- host/class/cdc/esp_modem_usb_dte/CHANGELOG.md
- host/class/cdc/esp_modem_usb_dte/include/esp_modem_usb_config.h
Added:
* SimCom SIM7070G modem
> feat(modem_usb): Add default configuration for more modems

- .github/ISSUE_TEMPLATE/bug-report.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature-request.yml
- .github/ISSUE_TEMPLATE/other-issue.yml
- .github/PULL_REQUEST_TEMPLATE/new_component.md
- .github/PULL_REQUEST_TEMPLATE/update_component.md
- .github/workflows/issue_comment.yml
- .github/workflows/new_issues.yml
- .github/workflows/new_prs.yml
- .github/workflows/test_sbom.yml
- README.md
Adding github workflows and the main `README.md`.
Everything transferred from `idf-extra-components` with minor changes like (paths, descriptions)
> refactor: Add github workflows

- .github/ci/override_managed_component.py
- .github/workflows/build_idf_examples.yml
Build esp-idf USB device examples in esp-usb CI
> feat(ci): Build ESP-IDF examples in esp-usb CI

- host/class/msc/usb_host_msc/src/msc_host.c
Fix for espressif/esp-idf issue #14319 [USB Host MSC: USB thumb drive cannot be initialized (IDFGH-13412) #14319](https://github.com/espressif/esp-idf/issues/14319)
When `TEST UNIT READY`, some USB Drives and SD Card Readers respond with sense_key: 0x06, code: 0x28, qualifier: 0x00 `NOT READY TO READY TRANSITION - MEDIA CHANGED`. In order to clear this code, a `REQUEST SENSE` needs to be performed before repeating `TEST UNIT READY`.
If the unit is ready, there is a quick return from the `msc_wait_for_ready_state` function. The previous code caused a minimum 100ms delay before returning, even if the MSC device was ready.
`WAIT_FOR_READY_TIMEOUT_MS` was increased to 5000ms, because some USB Drives were timing out with the old value of 3000ms.
---
Before submitting a Pull Request, please …
> Fix for /espressif/esp-idf issue #14319 (USB Host MSC: USB thumb drive cannot be initialized [IDFGH-13412]) (IEC-231)

- host/class/msc/usb_host_msc/CHANGELOG.md
- host/class/msc/usb_host_msc/idf_component.yml
Release MSC Class Driver v1.1.3
Changes: 
1. Implemented request sense, to get sense data from USB device in case of an error
2. Fixed initialization of some flash drives, which require more time to initialize
Fixed https://github.com/espressif/esp-idf/issues/14319 
---
> MSC Class Host Driver v1.1.3

- .github/workflows/build_and_run_test_app_usb.yml
This MR adds CI build and CI target test for IDF v5.4
To pass the CI run
---
> feat(ci): Add IDF 5.4 to CI run

- .github/workflows/clang-tidy.yml
This MR fixes failing Clang tidy job in CI
---
> fix(ci): Fix install pyclang in run clang tidy in CI

- host/class/cdc/usb_host_cdc_acm/test_app/main/test_cdc_acm_host.c
Fix failing CI for cdc-acm target tests on IDF 5.4
---
> fix(usb_host_cdc): Fix target test CI for IDF 5.4

- .github/workflows/build_and_run_host_test.yml
- .github/workflows/build_and_run_test_app_usb.yml
- .github/workflows/build_idf_examples.yml
- .github/workflows/clang-tidy.yml
Relevant information: in https://github.com/actions/runner-images/issues/11101
> ci: Update runners image to ubuntu-latest

- .build-test-rules.yml
- host/class/uac/usb_host_uac/CHANGELOG.md
- host/class/uac/usb_host_uac/host_test/CMakeLists.txt
- host/class/uac/usb_host_uac/host_test/README.md
- host/class/uac/usb_host_uac/host_test/main/CMakeLists.txt
- host/class/uac/usb_host_uac/host_test/main/idf_component.yml
- host/class/uac/usb_host_uac/host_test/main/test_main.cpp
- host/class/uac/usb_host_uac/host_test/main/test_unit_public_api.cpp
- host/class/uac/usb_host_uac/host_test/sdkconfig.defaults
- host/class/uac/usb_host_uac/idf_component.yml
- host/class/uac/usb_host_uac/include/usb/uac_host.h
- host/class/uac/usb_host_uac/uac_descriptors.c
- host/class/uac/usb_host_uac/uac_host.c
This MR adds:
- Linux target build for UAC host driver
- Host test for UAC Host driver (mainly fro the purposes of Linux target build)
- Preceded by #145 
- Closes #143 
Added host tests
---
> feat(uac_host): Add linux target build

- host/class/uvc/usb_host_uvc/host_test/README.md
- host/class/uvc/usb_host_uvc/host_test/main/CMakeLists.txt
- host/class/uvc/usb_host_uvc/host_test/main/opening/test_opening.cpp
- host/class/uvc/usb_host_uvc/host_test/main/test_fixtures.cpp
- host/class/uvc/usb_host_uvc/host_test/main/test_fixtures.hpp
- host/class/uvc/usb_host_uvc/private_include/uvc_idf_version_priv.h
- host/class/uvc/usb_host_uvc/uvc_descriptor_parsing.c
Simple UVC device opening mock
> test(host/uvc): Simple mock for opening UVC device

- host/class/uvc/usb_host_uvc/CHANGELOG.md
- host/class/uvc/usb_host_uvc/idf_component.yml
> release(host/uvc): v2.2.0

- .github/workflows/build_and_run_test_app_usb.yml
Cherry-picked from https://github.com/espressif/esp-usb/pull/163
> fix(ci): Temporarily disable IDF Latest in CI

- host/class/uvc/usb_host_uvc/host_test/main/streaming/images/test_logo_jpg.hpp
- host/class/uvc/usb_host_uvc/host_test/main/streaming/test_streaming.cpp
- host/class/uvc/usb_host_uvc/host_test/main/streaming/test_streaming_helpers.hpp
- host/class/uvc/usb_host_uvc/uvc_bulk.c
Closes IDF-12702
Alse clean-up the streaming host tests
> fix(uvc): Relax bulk EoF flag check

- host/class/uvc/usb_host_uvc/CHANGELOG.md
- host/class/uvc/usb_host_uvc/idf_component.yml
> release(host/uvc): v2.3.0

- .idf_build_apps.toml
- device/esp_tinyusb/test_apps/usb_cv/CMakeLists.txt
- device/esp_tinyusb/test_apps/usb_cv/main/CMakeLists.txt
- device/esp_tinyusb/test_apps/usb_cv/main/device_common.c
- device/esp_tinyusb/test_apps/usb_cv/main/device_common.h
- device/esp_tinyusb/test_apps/usb_cv/main/idf_component.yml
- device/esp_tinyusb/test_apps/usb_cv/main/storage_common.c
- device/esp_tinyusb/test_apps/usb_cv/main/storage_common.h
- device/esp_tinyusb/test_apps/usb_cv/main/test_app_main.c
- device/esp_tinyusb/test_apps/usb_cv/main/test_usbcv.c
- device/esp_tinyusb/test_apps/usb_cv/partitions.csv
- device/esp_tinyusb/test_apps/usb_cv/sdkconfig.defaults
- docs/device/usbcv_results/USBCV_Chapter9_xHCI_FS.html
- docs/device/usbcv_results/USBCV_Chapter9_xHCI_HS.html
- docs/device/usbcv_results/USBCV_HID_xHCI_FS.html
- docs/device/usbcv_results/USBCV_HID_xHCI_HS.html
- docs/device/usbcv_results/USBCV_MSC_xHCI_FS.html
- docs/device/usbcv_results/USBCV_MSC_xHCI_HS.html
Adding the USBCV test results to the `docs/device/usbcv_results` folder.
Results are: 
- 	`USBCV_Chapter9_xHCI_FS.html` - USB Chapter 9 tests on the xHCI with Full-speed device (S3)
- 	`USBCV_Chapter9_xHCI_HS.html` - USB Chapter 9 tests on the xHCI with High-speed device (P4)
- 	`USBCV_HID_xHCI_FS.html` - USB HID Class specific tests on the xHCI with Full-speed device (S3)
- 	`USBCV_HID_xHCI_HS.html` - USB HID Class specific tests on the xHCI with High-speed device (P4)
- 	`USBCV_MSC_xHCI_FS.html` - USB MSC Class specific tests on the xHCI with Full-speed device (S3)
- 	`USBCV_MSC_xHCI_HS.html` - USB MSC Class specific tests on the xHCI with High-speed device (P4)
N/A
usb_cv test application is provided to allow the user/programmer run the test application and run the USBCV test suite …
> feature(esp_tinyusb): USB Compliance Verification

- device/esp_tinyusb/CHANGELOG.md
Added the braking changes for v2.0.0 to the CHANGELOG  file. 
N/A
N/A
---
> docs(esp_tinyusb): Updated CHANGELOG for v2.0.0

- device/esp_tinyusb/README.md
- docs/device/migration-guides/v2/tinyusb.md
> fix(docs): Readme and migration guide cleanup

- host/class/uac/usb_host_uac/uac_host.c
This MR fixes `packed member address` (`unaligned pointer cast`) warning: `-Waddress-of-packed-member`, which is raised during linux target build and causes CI to fail.
<details>
<summary>Build warning</summary>
```
/__w/esp-usb/esp-usb/host/class/uac/usb_host_uac/uac_host.c: In function ‘uac_host_interface_suspend’:
/__w/esp-usb/esp-usb/host/class/uac/usb_host_uac/uac_host.c:1269:5: error: converting a packed ‘usb_setup_packet_t’ pointer (alignment 1) to a ‘uac_cs_request_t’ {aka ‘const struct uac_cs_request’} pointer (alignment 8) may result in an unaligned pointer value [-Werror=address-of-packed-member]
1269 |     esp_err_t ret = uac_cs_request_set(iface->parent, (uac_cs_request_t *)&request);
|     ^~~~~~~~~
In file included from …
```
> fix(uac_host): Fix linux target build warning

- .github/workflows/upload_component.yml
- #228 
- #223 
- Initial release of `usb_host_lib` component, (`usb` component ).
---
> release(usb_host_lib): v1.0.0-rc0

- device/esp_tinyusb/idf_component.yml
- esp_tinyusb: Added USB Compliance Verification results
- CDC-ACM: Added a configurable parameter for the endpoint DMA buffer
- esp_tinyusb: External PHY is no longer initialized automatically. If an external PHY is required, it must be explicitly initialized by the user with configuration parameter `phy.skip_setup = true`
- esp_tinyusb: Added run-time configuration for peripheral port selection, task settings, and descriptors. For more details, refer to the [Espressif's Addition to TinyUSB Mirgation guide v2](https://github.com/espressif/esp-usb/blob/master/docs/device/migration-guides/v2/tinyusb.md)
- esp_tinyusb: Added USB Device event callback to handle different USB Device events. For the list of supported USB Device events, refer to to [Espressif's Addition to TinyUSB - …
> release(esp_tinyusb): v2.0.0

- host/usb/CHANGELOG.md
- host/usb/idf_component.yml
Migrated usb component from esp-idf
- #238 
- #246
- #255
- #249 
---
> release(usb_host_lib): v1.0.0
