espressif/esp-usb

host/class/hid/usb_host_hid/CHANGELOG.md
host/class/hid/usb_host_hid/hid_host.c
host/class/hid/usb_host_hid/test/hid_mock_device.c

NOT A RELEASE 
- Refactored parsing Interfaces descriptor of the USB HID device. Fixed the crash, when USB HID device has two interfaces with inconsistent numbers (e.g. Device has two Interfaces with bInterfaceNumber=0 and bInterfaceNumber=2). 
Closes https://github.com/espressif/esp-idf/issues/13031

usb_host_hid v1.0.2: Fix USB HID device with multiple interfaces

---

host/class/hid/usb_host_hid/CHANGELOG.md
host/class/hid/usb_host_hid/CMakeLists.txt
host/class/hid/usb_host_hid/hid_host.c
host/class/hid/usb_host_hid/idf_component.yml

RELEASE
- String descriptor copying procedure doesn't use `wcsncpy` anymore. Now, there is no difference on sizeof(wchar_t) on different platforms (riscv, xtensa).
- Removed the flag `-Wno-address-of-packed-member` which was necessary for `wcsncpy`.

usb_host_hid v1.0.2: Support ESP32-P4

---

host/class/msc/usb_host_msc/CHANGELOG.md
host/class/msc/usb_host_msc/CMakeLists.txt
host/class/msc/usb_host_msc/idf_component.yml
host/class/msc/usb_host_msc/private_include/msc_common.h
host/class/msc/usb_host_msc/src/msc_host.c
host/class/msc/usb_host_msc/src/msc_scsi_bot.c

Fix MSC driver for P4
1. Correctly handle UTF-16 string descriptors
2. Revert zero-copy transfers. They cause issues with P4's L1 cache

usb_host_msc: Add P4 support

---

device/esp_tinyusb/CHANGELOG.md
device/esp_tinyusb/tusb_cdc_acm.c
device/esp_tinyusb/usb_descriptors.c

NOT A RELEASE 
- Removed MIN() macro definition if already defined (CDC-ACM)
- Changed the EP size for MSC class in default configuration descriptor (for HS)

esp_tinyusb: Removed MIN() definition if defined for cdc_acm

---

host/class/cdc/usb_host_cdc_acm/CHANGELOG.md
host/class/cdc/usb_host_cdc_acm/cdc_acm_host.c
host/class/cdc/usb_host_cdc_acm/include/usb/cdc_acm_host.h
host/class/cdc/usb_host_cdc_acm/test/test_cdc_acm_host.c

This bug was found out during esp-serial-flasher CDC operation.
In case the user does not track status of the CDC device and attempts to close the device from multiple places/threads the driver would crash
cc @DNedic

fix(cdc_acm): Fix closing of already closed device

---

device/esp_tinyusb/test/CMakeLists.txt
device/esp_tinyusb/test/test_bvalid_sig.c

NOT A RELEASE 
- Added a usb_device test for `bvalid_signal` verification. 
USB Device events, such as attach (plug) and detach (unplug) are detected via `bvalid_signal`, which can be connected to any (*mostly) external PIN. (In the most common cases, this external PIN connected to VBUS USB via resistor divider to detect the VBUS power presence. For reference, check [Self-Powered Device](https://docs.espressif.com/projects/esp-idf/en/v5.1.1/esp32s2/api-reference/peripherals/usb_device.html))
When USB Device (self-powered) is attached to the USB Host, the VBUS becomes High. 
When USB Device (self-powered) is detached from the USB Host, the VBUS becomes Low. 
Both of attach and detach, trigger the dcd_dwc2 layer interrupt with `DCD_EVENT_UNPLUGGED` event. 
Current test implement the USB …

esp_tinyusb: Adding bvalid_signal test

---

.pre-commit-config.yaml
check_copyright_config.yaml
device/esp_tinyusb/include/tusb_config.h
device/esp_tinyusb/test/test_bvalid_sig.c
device/esp_tinyusb/test/test_esp_tinyusb.c
host/class/cdc/usb_host_cdc_acm/test/test_cdc_acm_host.c
host/class/cdc/usb_host_cdc_acm/test/usb_device.c
host/class/hid/usb_host_hid/test/hid_mock_device.c
host/class/hid/usb_host_hid/test/hid_mock_device.h
host/class/msc/usb_host_msc/test/msc_device.c
host/class/msc/usb_host_msc/test/test_common.h
host/class/msc/usb_host_msc/test/test_msc.c
host/class/uvc/usb_host_uvc/include/libuvc_adapter.h
host/class/uvc/usb_host_uvc/include/libuvc_helper.h
host/class/uvc/usb_host_uvc/private_include/descriptor.h
host/class/uvc/usb_host_uvc/private_include/libusb.h
host/class/uvc/usb_host_uvc/src/descriptor.c
host/class/uvc/usb_host_uvc/test/test_uvc.c
test_app/pytest_usb_device.py
test_app/pytest_usb_host.py

Added copyright header check to pre-commit

CI: Add copyright license check

---

device/esp_tinyusb/test_app/main/test_bvalid_sig.c

Even though the `test_bvalid_sig` is not running in CI yet, I discovered this issue when refactoring the test app. 
The test was failing due to memory leak.
The problem was, that the tusb task was still running, after the test was finished.
Before:
```
MALLOC_CAP_8BIT: Before 385196 bytes free, After 380676 bytes free (delta -4520)
./main/test_bvalid_sig.c:20:bvalid_signal:FAIL:Function [esp_tinyusb][usb_device].  memory leak
```
Fixed:
```
MALLOC_CAP_8BIT: Before 385196 bytes free, After 385144 bytes free (delta -52)
MALLOC_CAP_32BIT: Before 385196 bytes free, After 385144 bytes free (delta -52)
```

Fix memory leak of the bvalid_sig test

---

host/class/uvc/usb_host_uvc/CHANGELOG.md
host/class/uvc/usb_host_uvc/README.md
host/class/uvc/usb_host_uvc/idf_component.yml
host/class/uvc/usb_host_uvc/include/libuvc_adapter.h
host/class/uvc/usb_host_uvc/src/descriptor.c
host/class/uvc/usb_host_uvc/src/libusb_adapter.c

- Added support for ESP32-P4
- Bumped libuvc version to relax frame format negotiation
- Fixed crash on opening non-UVC devices
Related
* libuvc PR https://github.com/libuvc/libuvc/pull/273
* Closes #19

UVC driver release 1.0.3

---

device/esp_tinyusb/CHANGELOG.md
device/esp_tinyusb/Kconfig
device/esp_tinyusb/descriptors_control.c
device/esp_tinyusb/idf_component.yml
device/esp_tinyusb/include/tinyusb.h
device/esp_tinyusb/include_private/descriptors_control.h
device/esp_tinyusb/include_private/usb_descriptors.h
device/esp_tinyusb/test/local/CMakeLists.txt
device/esp_tinyusb/test/local/libusb_test.c
device/esp_tinyusb/test_app/main/CMakeLists.txt
device/esp_tinyusb/test_app/main/test_bvalid_sig.c
device/esp_tinyusb/test_app/main/test_bvalid_sig.h
device/esp_tinyusb/test_app/main/test_descriptors_config.c
device/esp_tinyusb/test_app/main/test_descriptors_config.h
device/esp_tinyusb/test_app/main/test_tud_cb.c
device/esp_tinyusb/tinyusb.c
device/esp_tinyusb/usb_descriptors.c

- USB Device now able to work with both Hosts: High Speed (HS) or Full Speed (FS)
- Moved all the descriptor preparation logic inside `descriptor_control.c` file, `tinyusb_set_descriptors(..)`. This function is responsible for descriptors preparation based on the tinyusb configuration, provided during tinyusb driver install.
- Renamed default descriptors from `*_kconfig` to `*_default`.
- Added `descriptor_hs_cfg_default[]` for HighSpeed device and  `descriptor_hs_cfg_default[]` for FullSpeed device.
- Added `.hs_cfg_desc` field to tinyusb configuration (only when `TUD_OPT_HIGH_SPEED` is set)
- Added `.qualifier_desc` field to tinyusb configuration (only when `TUD_OPT_HIGH_SPEED` is set)
Configuration descriptor definitions: 
1. **FS only**
1.1 Configuration descriptor NOT present …

esp_tinyusb v1.4.4: Adding FS configuration descriptor for HS device

---

.github/PULL_REQUEST_TEMPLATE/new_component.md
.github/filter_sarif.py
.github/workflows/clang-tidy.yml
.gitignore
README.md
clang_tidy/CMakeLists.txt
clang_tidy/README.md

Adding Clang tidy related files.
We wanted to reuse Clang tidy CI job from `idf-extra-components`, where Clang tidy job was run from its main `test_app`.
Since we have split the main `test_app` into into several test apps in this respository an extensive Clang tidy job rework would be needed to run Clang tidy in all the test_apps. 
We decided to create a folder `clang_tidy`, from where Clang tidy is run. Doing so, nearly no modification is needed to be done in the Clang tidy CI job from `idf-extra-components`
`.github/filter_sarif.py` - copy from `idf-extra-components` (no modification)
`.github/workflows/clang-tidy.yml` - copy from `idf-extra-components` (line 41 added, line 38 modified folder name)
`clang_tidy` folder name and content of `clang_tidy/README.md` is opened for discussion.

CI: Add Clang tidy

---

host/class/uvc/usb_host_uvc/CHANGELOG.md
host/class/uvc/usb_host_uvc/idf_component.yml
host/class/uvc/usb_host_uvc/src/descriptor.c

1. support print `format frame based` descriptor
2. support print `frame frame based` descriptor

UVC driver release 1.0.4 (IEC-104)

---

.github/workflows/clang-tidy.yml

Following up with a fix from [idf-extra-components](https://github.com/espressif/idf-extra-components/pull/333)

ci: remove libtinfo5 installation

---

.github/workflows/build_and_run_test_app_usb.yml

Closes [IDF-9867](https://jira.espressif.com:8443/browse/IDF-9867)
This MR adds IDF 5.3 to the CI build and target run

CI: Add build and target run for IDF_v5.3

---

.gitmodules
device/esp_tinyusb/CHANGELOG.md

This PR changes our libuvc submodule from upstream https://github.com/libuvc/libuvc to Espressif's fork https://github.com/espressif/libuvc
Please note that this deployment strategy is different from TinyUSB, where we release TinyUSB as one component and TinyUSB additions as a second one. This approach brings a lot of maintenance effort, though. So, IMO, this simplified strategy is more suitable for UVC
Opinions welcome!

UVC deployment strategy (for discussion)

---

host/class/msc/usb_host_msc/CHANGELOG.md
host/class/msc/usb_host_msc/src/msc_scsi_bot.c

Closing IDF-9890
Added request sense feature for MCS driver.
After each  BOT command execution a `CSW` is checked for possible errors. If an error is present in the MSC device a `bCSWStatus` is returned to the Host as non zero. Ref: [USB Mass Storage Class – Bulk Only Transport](https://www.usb.org/sites/default/files/usbmassbulk_10.pdf) table 5.3. But a current MSC Host driver does not allow the user to find out what is causing the error.
This MR adds a feature to the MSC Host to issue a request sense to the MSC device each time, after checking `CSW` for errors. The request sense command returns specific error code. Ref: [USB Mass Storage Class – UFI Command Specification](https://www.usb.org/sites/default/files/usbmass-ufi10.pdf) Chapter 4.11 and Table 51

USB Host MSC: Add request sense feature

---

host/class/cdc/esp_modem_usb_dte/CHANGELOG.md
host/class/cdc/esp_modem_usb_dte/CMakeLists.txt
host/class/cdc/esp_modem_usb_dte/README.md
host/class/cdc/esp_modem_usb_dte/idf_component.yml
host/class/cdc/esp_modem_usb_dte/include/esp_modem_usb_config.h

Closes https://github.com/espressif/esp-usb/pull/30

feat(esp_modem_usb_dte): add esp32p4 support & add cat.4 ec20 modem

---

host/class/cdc/usb_host_cdc_acm/CHANGELOG.md
host/class/cdc/usb_host_cdc_acm/cdc_acm_host.c
host/class/cdc/usb_host_cdc_acm/idf_component.yml
host/class/cdc/usb_host_cdc_acm/test_app/main/test_cdc_acm_host.c

After TX transfer timeout we reset the endpoint which causes all in-flight transfers to complete. The transfer finished callback gives a transfer finished semaphore which we must take, so we would not affect next TX transfers.
Test included
Closes https://github.com/espressif/esp-protocols/issues/514
Closes https://github.com/espressif/esp-usb/pull/40
Closes https://github.com/espressif/esp-idf/issues/13797

fix(host/cdc): Fix TX timeout reaction

---

host/class/cdc/esp_modem_usb_dte/CHANGELOG.md
host/class/cdc/esp_modem_usb_dte/esp_modem_usb.cpp
host/class/cdc/esp_modem_usb_dte/idf_component.yml

usb host (CDC ACM) does not allow sending more data than the configured `out_xfer->data_buffer_size`.
Modem terminal, however, expects that we could send bigger chunks of data in both data and command mode (it's already supported in both inherent esp_modem terminals: UART, VFS)
* Closes https://github.com/espressif/esp-protocols/issues/589
* Alternative to https://github.com/espressif/esp-protocols/pull/593

feat(cdc/modem): Add support to write big payloads in chunks (IEC-128)

---

host/class/cdc/usb_host_vcp/CMakeLists.txt
host/class/cdc/usb_host_vcp/idf_component.yml

After upgrading to gcc14 i faced this issue: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=116070
There is a solution to suppress the errors, but I don't know if you happy with these changes and why the default gnu++XX standard derived from idf could not be used...
P.s.: This change looks valid to me if take into account: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=116071#c2

feat(cdc): fix compilation with GCC14 (IEC-138)

---

host/class/cdc/usb_host_vcp/CMakeLists.txt
host/class/cdc/usb_host_vcp/idf_component.yml

Related to https://github.com/espressif/esp-usb/pull/47
Sorry I set wrong gcc version variable for CMake in prior PR :(
@tore-espressif

feat(cdc): fix GCC version variable name for CMake (IEC-151)

---

.github/workflows/build_and_run_test_app_usb.yml

Fix idf-component-manager build with IDF v4.4
Idf-component-manager v2.0.0 was released yesterday and it is not compatible with IDF v4.4

fix(ci): Do not upgrade idf-component-manager

---

host/class/uac/usb_host_uac/CHANGELOG.md
host/class/uac/usb_host_uac/CMakeLists.txt
host/class/uac/usb_host_uac/Kconfig
host/class/uac/usb_host_uac/idf_component.yml
host/class/uac/usb_host_uac/include/usb/uac_host.h
host/class/uac/usb_host_uac/test_app/main/test_host_uac.c
host/class/uac/usb_host_uac/uac_host.c

- Added add `uac_host_device_open_with_vid_pid` to open connected audio devices with known VID and PID
- Print component version message `uac-host: Install Succeed, Version: 1.1.0` in `uac_host_install` function

feat(host_uac): support open device with known vid pid

---

host/class/cdc/usb_host_cdc_acm/CHANGELOG.md
host/class/cdc/usb_host_cdc_acm/cdc_acm_host.c

Some devices have MaxPacketSize0 = 8 which is not enough for some CDC specific CTRL requests
Closes https://github.com/espressif/esp-idf/issues/14345

fix(host/cdc_acm): Fix CTRL transfer size for devices with small MaxPacketSize0

---

host/class/hid/usb_host_hid/CHANGELOG.md
host/class/hid/usb_host_hid/hid_host.c
host/class/hid/usb_host_hid/idf_component.yml

- Initial support for external Hubs
1. Fixed a bug with interface mismatch on EP IN transfer complete while several HID devices are present.
2. Fixed a bug during device freeing, while detaching one of several attached HID devices.
1. Wrong interface has been selected by EP number, while handling transfer complete callback for EP IN of HID Device. Fully removed logic of getting interface by EP number, instead keep the interface pointer in `xfer->context` field. 
2.  Wrong logic of releasing and freeing HID device object during device detaching. When several device were attached, the STAILQ was never empty, so the driver hanged infinitely.

HID driver release 1.0.3

---

host/class/cdc/usb_host_vcp/CMakeLists.txt
host/class/cdc/usb_host_vcp/idf_component.yml

@tore-espressif , sorry for bothering again. I was able to build test app locally because of bug IDF-10801.
To make pipeline pass for gcc14 this change is required

feat(cdc): fix compilation with GCC14 (IEC-153)

---

.github/workflows/build_and_run_test_app_usb.yml
.github/workflows/build_idf_examples.yml
.github/workflows/clang-tidy.yml
.github/workflows/issue_comment.yml
.github/workflows/new_issues.yml
.github/workflows/new_prs.yml
.github/workflows/pre-commit.yml
.github/workflows/test_sbom.yml
.github/workflows/upload_component.yml

Update GH actions with security fixes

ci: Update GitHub Actions' versions

---

host/class/msc/usb_host_msc/src/msc_host.c

Cleanup debug output in MSC class driver.
* Closes IDF-9047
N/A
---

fix(usb_host_msc): Changed HID -> MSC in debug output

---

host/class/cdc/usb_host_cdc_acm/CHANGELOG.md
host/class/cdc/usb_host_cdc_acm/README.md
host/class/cdc/usb_host_cdc_acm/cdc_acm_host.c
host/class/cdc/usb_host_cdc_acm/idf_component.yml
host/class/cdc/usb_host_cdc_acm/include/usb/cdc_acm_host.h
host/class/cdc/usb_host_cdc_acm/test_app/main/test_cdc_acm_host.c

The CDC driver must support also devices who do not follow the CDC specification. Any many cases, the user does not know or care about the device's VID/PID. With this feautere, any device can be opened
A test is added that checks all positive (device opened) and negative (device not opened) cases

Add option to open a CDC device with any VID or PID

---

host/class/cdc/usb_host_cdc_acm/host_test/main/cdc_descriptors.hpp
host/class/cdc/usb_host_cdc_acm/host_test/main/test_parsing_modems.cpp

Tests modem descriptor parsing from https://github.com/espressif/esp-usb/issues/76

feat(cdc_acm): Add SimCom A7672 modem to descriptor tests

---

host/class/uac/usb_host_uac/CHANGELOG.md
host/class/uac/usb_host_uac/Kconfig
host/class/uac/usb_host_uac/idf_component.yml
host/class/uac/usb_host_uac/include/usb/uac_host.h
host/class/uac/usb_host_uac/test_app/main/test_host_uac.c
host/class/uac/usb_host_uac/uac_host.c

Release UAC Class Driver v1.2.0
> * For UAC devices, the correct way to configure the volume is first to obtain the maximum, minimum (a subset ranging from +127.9961 dB (0x7FFF) to -127.9961 dB (0x8001)), and step values. Then SET_CUR with the 16-bit db value (Please check UAC1.0 Spec Page.77 for details). v1.2.0 provides the standard implementation. 
1. Changed the parameter type of `uac_host_device_set_volume_db` from uint32_t to int16_t
1. Support get current volume and mute status
1. Fixed incorrect volume conversion. Using actual device volume range.
2. Fixed concurrency issues when suspend/stop during read/write
Unitest Pass in both ESP32-S3 and ESP32-P4
---

UAC Class Host Driver v1.2.0

---

.build-test-rules.yml
host/class/cdc/usb_host_cdc_acm/host_test/main/test_unit_public_api.cpp
host/class/hid/usb_host_hid/hid_host.c
host/class/hid/usb_host_hid/host_test/CMakeLists.txt
host/class/hid/usb_host_hid/host_test/README.md
host/class/hid/usb_host_hid/host_test/main/CMakeLists.txt
host/class/hid/usb_host_hid/host_test/main/idf_component.yml
host/class/hid/usb_host_hid/host_test/main/test_unit_public_api.cpp
host/class/hid/usb_host_hid/host_test/sdkconfig.defaults
host/class/hid/usb_host_hid/idf_component.yml
host/class/uvc/usb_host_uvc/host_test/CMakeLists.txt
host/class/uvc/usb_host_uvc/host_test/README.md
host/class/uvc/usb_host_uvc/host_test/main/CMakeLists.txt
host/class/uvc/usb_host_uvc/host_test/main/idf_component.yml
host/class/uvc/usb_host_uvc/host_test/main/test_unit_public_api.cpp
host/class/uvc/usb_host_uvc/host_test/sdkconfig.defaults
host/class/uvc/usb_host_uvc/idf_component.yml
host/class/uvc/usb_host_uvc/include/libuvc_helper.h
host/class/uvc/usb_host_uvc/src/libusb_adapter.c

As a part of Linux host testing, we have created a mock of USB component in the esp-idf, which will be used for testing of Class drivers within this (esp-usb) repository using Cmock test cases. 
- HID Host
- UVC Host
- CDC ACM Host
- MSC Host - `vfs` not buildable for linux
- UAC Host - Ringbuffer support missing in Freerots Cmock
- esp_tinyusb - `vfs` not buildable for linux
As discussed, rather than adding new supported target into the `idf_component.yml` file, (`linux` in this case, and other targets in future) the target list was removed from (those class drivers buildable for linux) and a target compatibility will be handled during build.
- HID Host linux build + simple cmock unit test
- UVC Host linux build + simple cmock unit test
- CDC ACM simple cmock unit test
-  IDF-10351 - USB …

feat(cmock): Enable linux target build for HID, CDC-ACM and UVC hosts

---

.github/workflows/build_and_run_test_app_usb.yml

In https://github.com/espressif/esp-usb/pull/75 we refactored the test runners' configuration. We want to run the test more frequently so we can evaluate their stability.
This entire commit can be reverted after the evaluation period is over (in couple of weeks).

feat(ci): Build and run target tests everyday

---

.github/workflows/build_idf_examples.yml
device/esp_tinyusb/test_apps/vendor/main/test_vendor.c

USB Device Vendor specific class driver API changed from v0.16.0 to v0.17.0.
`void tud_vendor_rx_cb(uint8_t itf)` - > `void tud_vendor_rx_cb(uint8_t itf, uint8_t const *buffer, uint16_t bufsize)`
To build `test_apps` from esp_tinyusb component with tinyusb component, with v0.17.0.1 or higher, the test_app code should be changed accordingly. 
- Caused by `espressif/tinyusb` [v0.17.0~1](https://github.com/espressif/tinyusb/tree/v0.17.0.1)
---

change(test_vendor): Compatibility with tinyusb v0.17.x and higher 

---

.github/workflows/build_and_run_test_app_usb.yml
host/class/cdc/usb_host_cdc_acm/test_app/README.md
host/class/cdc/usb_host_cdc_acm/test_app/main/test_app_main.c
host/class/cdc/usb_host_cdc_acm/test_app/main/test_cdc_acm_host.c
host/class/cdc/usb_host_cdc_acm/test_app/main/usb_device.c
host/class/cdc/usb_host_cdc_acm/test_app/pytest_usb_host_cdc.py
host/class/hid/usb_host_hid/test_app/README.md
host/class/hid/usb_host_hid/test_app/main/hid_mock_device.c
host/class/hid/usb_host_hid/test_app/main/test_app_main.c
host/class/hid/usb_host_hid/test_app/main/test_hid_basic.c
host/class/hid/usb_host_hid/test_app/pytest_usb_host_hid.py
host/class/msc/usb_host_msc/test_app/README.md
host/class/msc/usb_host_msc/test_app/main/msc_device.c
host/class/msc/usb_host_msc/test_app/main/test_app_main.c
host/class/msc/usb_host_msc/test_app/main/test_common.h
host/class/msc/usb_host_msc/test_app/main/test_msc.c
host/class/msc/usb_host_msc/test_app/pytest_usb_host_msc.py
host/class/uvc/usb_host_uvc/test_app/README.md
host/class/uvc/usb_host_uvc/test_app/main/test_app_main.c
host/class/uvc/usb_host_uvc/test_app/pytest_usb_host_uvc.py

This MR enables class drivers test apps, to be run on esp32p4
- New `esp32p4` `usb_host` target runner `BrnoVM0114` was added to the CI
- Enabled test apps build and run in CI for esp32p4
- Memory leak checks evaluation during test case teardown updated to new API
- removed all code in test apps related to IDF versions lower than 5.0
- `usb_host_lib_set_root_port_power` function used to toggle connection of USB devices must be used for esp32p4, but has been implemented only in `IDF 5.2`
- for IDF versions lower than 5.3, the old way of connection toggling (using PHY) is used, because esp32p4 has been added from `IDF 5.3`
- for IDF versions higher than, including 5.3, the new way of connection toggling (using root power) is used.
-  RDT-995 Add new esp32p4 usb_host runner
-  IDF-11346 …

ci(usb_host): Class drivers test apps run on esp32p4

---

.github/workflows/build_and_run_test_app_usb.yml
device/esp_tinyusb/test_apps/cdc_and_usb_device/main/test_bvalid_sig.c
device/esp_tinyusb/test_apps/cdc_and_usb_device/main/test_cdc.c
device/esp_tinyusb/test_apps/cdc_and_usb_device/main/test_descriptors_config.c

This MR enables `esp_tinyusb` tests in CI on a new `usb_device` `esp32p4` runner.
The new runner `BrnoRPIG009` was updated with a script introduced in #75, allowing us to access USB devices from running docker container.
In esp_tinyusb, there are 3 groups of tests:
- `pytest_cdc.py` - Test is run in CI
- `pytest_usb_device.py` - Test not run in CI, missing teradown function in tinyusb (also bvalid signal test not tested on esp32p4)
- `pytest_vendor.py` - Test not run in CI due to Docker container problems accessing a vendor specific device
- IDF-11684 Run esp_tinyusb tests on esp32p4 in GH CI
- IDF-11345 Run esp_tinyusb tests in GH CI
- IDF-11804 Invesitagate usage of VBUS monitor on HS PHY for esp32p4
To pass current CI tests
---
Before submitting a Pull Request, please ensure the …

ci(tinyusb): Run tinyusb tests in CI for esp32p4

---

device/esp_tinyusb/CHANGELOG.md
device/esp_tinyusb/Kconfig
device/esp_tinyusb/include/tusb_config.h

DMA support for TinyUSB device stack. 
DMA (Buffer mode) is a default mode for device, meanwhile there is an option to change the mode to Single/IRQ by disabling DMA mode via menuconfig. 
If (by any reason) hardware isn't support DMA (`arch != GHWCFG2_ARCH_INTERNAL_DMA`) then the Single/IRQ mode will be used. 
* Related to https://github.com/espressif/tinyusb/pull/37
* Closes https://github.com/espressif/esp-idf/issues/11161
This PR is already compatible with the branch: https://github.com/espressif/tinyusb/tree/release/v0.17
Measurements were made on `tusb_msc` example (read-write operations benchmark, SDMMC target).
| MSC Buffer size (bytes)   |      Slave Mode (R/W)      |  Buffer DMA (R/W) |
|:----------:|:-------------:|:------:|
| 512 |  503.4 kB/s / 187.2 kB/s  | 509.8 kB/s / …

feature(esp_tinyusb): Added mode configuration for dcd_dwc2 layer

---

device/esp_tinyusb/CHANGELOG.md
device/esp_tinyusb/Kconfig
device/esp_tinyusb/idf_component.yml

A problem could be present in a high-loaded systems (with several interfaces) and when large amounts of data were being sent and received simultaneously, the dcd_event_xfer_complete event was not triggered. 
Pinned tinyusb FreeRTOS task to CPU1 by default in the dual-core systems. 
- Releated to IDF-4552
N/A

fix(esp_tinyusb): Pinned tinyusb task to the CPU1 by default

---

host/class/msc/usb_host_msc/CHANGELOG.md
host/class/msc/usb_host_msc/include/usb/msc_host_vfs.h
host/class/msc/usb_host_msc/src/msc_host_vfs.c
host/class/msc/usb_host_msc/test_app/main/test_msc.c

Provide the possibility to format connected flash drive
Currently the flash drive should be formatted in advance, otherwise it can be formatted by ESP when mount error is present. To have the possibility to format connected flash drives in the USB Host MSC class driver explicitly, the new API call has been added. Now, the format process of the flash drive can be done not only during the mounting failure (format_if_mount_failed and FR_NO_FILESYSTEM) but explicitly from the application logic.
- Closes https://github.com/espressif/esp-idf/issues/14890
- IDFGH-14076 Missing option for USB MSC drive format
Added test case for testing public API.
---

feat(msc_host): Add format MSC support

---

device/esp_tinyusb/CHANGELOG.md
device/esp_tinyusb/tusb_cdc_acm.c

Common sequence for tinyusb CDC driver install: 
1. `tinyusb_driver_install()`
2. `tusb_cdc_acm_initialized()`
3. `tusb_cdc_acm_init()`
During the `tusb_cdc_acm_init()` the internal object `cdc_inst->subclass_obj` is allocated. 
And doesn't freeing during the common uninstall:
1. `tusb_cdc_acm_deinit()`
2. `tinyusb_driver_uninstall()`
- Implemented new static function: `obj_free(itf)`, which is the freeing mechanism for function `alloc_obj(itf)`
- Added the `obj_free(itf)` call while `tusb_cdc_acm_deinit()`
And during these steps there is no freeing present. 
- Was found in https://github.com/espressif/esp-usb/pull/39
- eps_tinyusb teardown PR: https://github.com/espressif/esp-usb/pull/39
---

fix(tusb_cdc): Added freeing cdc object

---

.github/workflows/build_and_run_test_app_usb.yml
device/esp_tinyusb/include/tinyusb.h
device/esp_tinyusb/test_apps/cdc_and_usb_device/main/test_bvalid_sig.c
device/esp_tinyusb/test_apps/cdc_and_usb_device/main/test_descriptors_config.c
device/esp_tinyusb/test_apps/teardown_device/CMakeLists.txt
device/esp_tinyusb/test_apps/teardown_device/main/CMakeLists.txt
device/esp_tinyusb/test_apps/teardown_device/main/idf_component.yml
device/esp_tinyusb/test_apps/teardown_device/main/test_app_main.c
device/esp_tinyusb/test_apps/teardown_device/main/test_teardown.c
device/esp_tinyusb/test_apps/teardown_device/pytest_teardown_device.py
device/esp_tinyusb/test_apps/teardown_device/sdkconfig.defaults
device/esp_tinyusb/tinyusb.c

- To uninstall tinyusb driver, a teardown tinyusb stack should be called. 
- `tud_deinit()` feature was implemented in upstream, starting with version v0.17.0.
- Added `tusb_teardown()` call while `tinyusb_driver_uninstall()` 
- Added test app to verify teardown feature
1. Install TinyUSB device without any class
2. Wait SetConfiguration() (tud_mount_cb)
3. If attempts == 0 goto step 8
4.   Wait TEARDOWN_DEVICE_DETACH_DELAY_MS
5.   Uninstall TinyUSB device
6.   Wait TEARDOWN_DEVICE_INIT_DELAY_MS
7.   Decrease attempts by 1, goto step 3
8. Wait TEARDOWN_DEVICE_DETACH_DELAY_MS
9. Uninstall TinyUSB device
Notes: 
- when amount of teardown configured to 0, then only one install-uninstall routine is fulfilled. 
- device presence used subprocess call "lsusb" and check the Espressif VID/PIN in …

feature(esp_tinyusb): Added tusb_teardown() call while tinyusb_driver_uninstall() 

---

device/esp_tinyusb/CHANGELOG.md
device/esp_tinyusb/idf_component.yml

- Added support of  `tusb_teardown()` during uninstall
- Fixed memory leakage during CDC ACM uninstall
- https://github.com/espressif/esp-usb/pull/105
- https://github.com/espressif/esp-usb/pull/39
---

esp_tinyusb v1.6.0

---

.github/workflows/build_and_run_test_app_usb.yml

Fail fast on matrix jobs.
This will offload the test runner if the tests are not passing

ci: Fail fast to offload runners

---

device/esp_tinyusb/CHANGELOG.md
device/esp_tinyusb/Kconfig
device/esp_tinyusb/include/tusb_config.h

This MR adds a possibility to configure NCM transfer blocks via menuconfig.
A table below shows RAM usage and performance dependency on NTB buffers configuration, NTB buffers count and NTB buffers length. Memory occupation was measured using [NCM Device Example](https://github.com/espressif/esp-idf/tree/master/examples/peripherals/usb/device/tusb_ncm) on esp32s3.
| NTB Buffers count (IN/OUT) | 1/1             | 2/2             | 2/2           | 3/3             | 4/4            |
|--------------------------|-----------------|-----------------|---------------|-----------------|----------------|
| NTB Buffers length (IN/OUT)   | 3200/3200       | 3200/3200       | 6400/6400     | 8192/8192       | 8192/8192      |
| Used RAM [bytes]         | 112320          | 118736          | 131552 …

fix(esp_tinyusb): Fix NCM NTB buffers configuration

---

device/esp_tinyusb/CHANGELOG.md
device/esp_tinyusb/Kconfig
device/esp_tinyusb/tinyusb.c

Added possibility to select the USB OTG1.1 Peripheral (FS) on ESP32P4 via menuconfig.
N/A
Could be tested only on correct P4 board. 
- This changes are available only after removing `usb_phy_p4.c` in esp-idf. Removing the specific P4-related file additionally unlocks the possibility to initialize PHY for USB OTG1.1, which it necessary for USB OTG1.1 Peripheral.  

feature(esp_tinyusb): Added config option to select USB OTG1.1 periph on P4

---

device/esp_tinyusb/CHANGELOG.md
device/esp_tinyusb/idf_component.yml

- NCM: Added possibility to configure NCM Transfer Blocks (NTB) via menuconfig
- esp_tinyusb: Added option to select TinyUSB peripheral on esp32p4 via menuconfig (USB_PHY_SUPPORTS_P4_OTG11 in esp-idf is required)
- esp_tinyusb: Fixed uninstall tinyusb driver with not default task configuration
- https://github.com/espressif/esp-usb/pull/114
- https://github.com/espressif/esp-usb/pull/91
- https://github.com/espressif/esp-usb/pull/115
---

esp_tinyusb v1.7.0

---

.github/workflows/build_idf_examples.yml

Latest release v1.7.0 breaks the example/network/sta2eth build on ESP32S2. 
Reason: region `dram0_0_seg' overflowed by:
- 1336 bytes (in my local build)
- 2024 bytes (in the CI build) 
To prevent same result in the future, add example to the CI with all available versions of esp-idf
This is a 1/3 PR to fix the problem. 
PR plan: 
1. Add all esp-idf releases to the current CI build process (this PR)
2. Add network examples to the CI build process (https://github.com/espressif/esp-usb/pull/124)
3. Fix the NCM Driver memory usage on ESP32S2 (https://github.com/espressif/esp-usb/pull/125)
Several PR's could be merged after completion in one (or not).
N/A
---

ci(workflow): Added esp-idf releases matrix for examples build

---

device/esp_tinyusb/Kconfig

Default value for NCM NTB buffers were 3/3 of 8192 bytes, which led to DRAM overflow on ESP32S2 during the esp-idf sta2eth example build. 
Amount of memory, that could be used to hold NTB does depend on the application logic.
This is a 2/3 PR to fix the problem. 
To enable the build of the Network example, default value of the buffers amount for  transmission and reception side were changed to 1. 
Comparison values for `examples/network/sta2eth` to select the optimal buffer size and count. 
| Count(In/Out)  | Size(In/Out) | Remain DRAM (Bytes, %) | release |
| ------------- | ------------- | ------------- | ------------- |
| 3/3 | 3200/3200 |  35769 (20,3%)       | v5.2 |
| 3/3 | 3200/3200 |  28437 (11,53%)  | v5.3 |
| 3/3 | 3200/3200  | 31477 (18.3%)| v5.4 |
| 3/3 | 3200/3200 |  28008 …

fix(ncm): Changed NTB default value to fix DRAM overflow on esp32s2

---

.github/ci/override_managed_component.py
.github/workflows/build_idf_examples.yml

This PR updates the IDF Component Manager version in `.build_idf_examples.yml` and updates the import in `override_managed_component.py` 
* Closes [PACMAN-1051](https://jira.espressif.com:8443/browse/PACMAN-1051)
Changes were tested on a fork of the repository in Github Actions

ci: Update IDF Component Manager version (IEC-258)

---

host/class/uvc/usb_host_uvc/CHANGELOG.md
host/class/uvc/usb_host_uvc/idf_component.yml
host/class/uvc/usb_host_uvc/uvc_control.c
host/class/uvc/usb_host_uvc/uvc_descriptor_parsing.c
host/class/uvc/usb_host_uvc/uvc_host.c

Some UVC devices require to set alternate setting to 0 before the negotiation starts.
Closes https://github.com/espressif/esp-idf/issues/9868

fix(host/uvc): Fixed negotiation for some non-conforming UVC devices

---

host/class/uvc/usb_host_uvc/CHANGELOG.md
host/class/uvc/usb_host_uvc/Kconfig
host/class/uvc/usb_host_uvc/idf_component.yml
host/class/uvc/usb_host_uvc/include/usb/uvc_host.h
host/class/uvc/usb_host_uvc/private_include/uvc_descriptors_priv.h
host/class/uvc/usb_host_uvc/uvc_descriptor_parsing.c
host/class/uvc/usb_host_uvc/uvc_descriptor_printing.c
host/class/uvc/usb_host_uvc/uvc_host.c

Feature: 
1. Fixed the issue where connecting to the hub would automatically power it on.
2. Added a callback: When a USB camera device is inserted, notify the user with the VID, PID, and camera parameters.
3. Supported printing the complete USB descriptor for debugging when a new device is inserted.
4. Supported opening a specified device using `usb_handle` or `dev_addr`.
---

feat(usb_host_uvc): support dual camera with hub (IEC-246)

---

device/esp_tinyusb/CHANGELOG.md
device/esp_tinyusb/idf_component.yml
device/esp_tinyusb/tinyusb.c

* Bug in esp-idf: when external phy is selected, we cannot call set_speed()

fix(esp_tinyusb): Fix crash when external PHY is used

---

device/esp_tinyusb/CHANGELOG.md
device/esp_tinyusb/idf_component.yml

- esp_tinyusb: Fixed crash on logging from ISR
- PHY: Fixed crash with external_phy=true configuration
- https://github.com/espressif/esp-usb/pull/132
- https://github.com/espressif/esp-usb/pull/139
---

esp_tinyusb v1.7.2

---

device/esp_tinyusb/test_apps/configuration_desc/CMakeLists.txt
device/esp_tinyusb/test_apps/configuration_desc/main/CMakeLists.txt
device/esp_tinyusb/test_apps/configuration_desc/main/idf_component.yml
device/esp_tinyusb/test_apps/configuration_desc/main/test_app_main.c
device/esp_tinyusb/test_apps/configuration_desc/main/test_config_desc.c
device/esp_tinyusb/test_apps/configuration_desc/pytest_config_desc.py
device/esp_tinyusb/test_apps/configuration_desc/sdkconfig.defaults

Split the test application for cdc and disconnection verification.
Part2/2: Added the test_app for tinyusb various configurations
- Part 1/2: https://github.com/espressif/esp-usb/pull/108 
- Added a test for various tinyusb configurations (FS/HS)
---

refactor(config_test): Added the test_app for various configurations (part 2/2)

---

host/class/uac/usb_host_uac/test_app/main/test_host_uac.c

This MR fixes UAC Host test app build in CI. 
`usb_phy_action()` originally used for forcing connection and disconnection in test apps, is now deprecated, which is causing build errors in CI.
`usb_host_lib_set_root_port_power()` is used instead of the `usb_phy_action()`
Also, it is not possible to use `usb_phy_action()` on esp32p4 targert, because the P4's PHY can't be controlled in the same way as the S3's and S2's PHY
<details>
<summary>An error from CI build for IDF latest fixed in this MR</summary>
```shell
2025-03-06T10:24:51.6003789Z /__w/esp-usb/esp-usb/host/class/uac/usb_host_uac/test_app/main/test_host_uac.c: In function 'force_conn_state':
2025-03-06T10:24:51.6004616Z /__w/esp-usb/esp-usb/host/class/uac/usb_host_uac/test_app/main/test_host_uac.c:75:5: error: 'usb_phy_action' is …
```

fix(uac_host): Fix deprecated warning in test app

---

host/class/uvc/usb_host_uvc/CHANGELOG.md
host/class/uvc/usb_host_uvc/README.md
host/class/uvc/usb_host_uvc/examples/basic_uvc_stream/main/basic_uvc_stream.c
host/class/uvc/usb_host_uvc/host_test/main/streaming/test_streaming.cpp
host/class/uvc/usb_host_uvc/include/usb/uvc_host.h
host/class/uvc/usb_host_uvc/private_include/uvc_frame_priv.h
host/class/uvc/usb_host_uvc/private_include/uvc_types_priv.h
host/class/uvc/usb_host_uvc/uvc_bulk.c
host/class/uvc/usb_host_uvc/uvc_frame.c
host/class/uvc/usb_host_uvc/uvc_host.c
host/class/uvc/usb_host_uvc/uvc_isoc.c

Support modifying the requested resolution without reopening the UVC device.
* New function `esp_err_t uvc_host_stream_format_select(uvc_host_stream_hdl_t stream_hdl, uvc_host_stream_format_t *format);` that allows change of video format of an opened stream
* Few minor optimizations and clean-ups in tests
All cameras that I tested do not support format change while streaming.
So in case the camera is streaming at the time the format change is requested, we stop the stream, reconfigure the stream format and start the stream again.

feat(host/uvc): Allow format change of open stream (IDF-12571)

---

host/class/uvc/usb_host_uvc/CHANGELOG.md
host/class/uvc/usb_host_uvc/include/esp_private/uvc_control.h
host/class/uvc/usb_host_uvc/uvc_control.c
host/class/uvc/usb_host_uvc/uvc_host.c

Fixed device opening and negotiation
Now the frame format is committed in uvc_host_stream_start().
This fixes some BULK cameras time-out after the format was committed
but the stream was not started within few seconds.

fix(host/uvc): Fixed stream opening procedure (IDF-12619)

---

device/esp_tinyusb/tusb_msc_storage.c

This MR adds a build time check for Wear leveling sector size. 
The WL sector size must be at least the size of the `CONFIG_TINYUSB_MSC_BUFSIZE`. otherwise the `msc_storage_write_sector()` function registered to `tud_msc_write10_cb()` callback would keep trying to write to the sector in an infinite loop, producing a following output:
```
E (25811) tinyusb_msc_storage: msc_storage_write_sector failed: 0x102
E (25821) tinyusb_msc_storage: Invalid Argument lba(0) offset(0) size(512) sector_size(4096)
```
In the `tusb_msc` example, the wear leveling sector size is set in `sdkconfig.defatults` to 512 [`CONFIG_WL_SECTOR_SIZE_512=y`](https://github.com/espressif/esp-idf/blob/master/examples/peripherals/usb/device/tusb_msc/sdkconfig.defaults#L10).
But the description in the wear leveling …

fix(tusb_msc): Check Wear leveling sector size during build

---

.github/workflows/build_and_run_test_app_usb.yml
.github/workflows/build_idf_examples.yml
device/esp_tinyusb/CHANGELOG.md
device/esp_tinyusb/idf_component.yml
device/esp_tinyusb/include/tinyusb.h
device/esp_tinyusb/test_apps/cdc/main/test_cdc.c
device/esp_tinyusb/test_apps/configuration_desc/main/test_config_desc.c
device/esp_tinyusb/test_apps/dconn_detection/main/test_dconn_detection.c
device/esp_tinyusb/test_apps/default_task/main/test_tusb.c
device/esp_tinyusb/test_apps/default_task_with_init/main/test_tusb.c
device/esp_tinyusb/test_apps/external_task/main/test_tusb.c
device/esp_tinyusb/test_apps/teardown_device/main/test_teardown.c
device/esp_tinyusb/test_apps/vendor/main/test_vendor.c
device/esp_tinyusb/tinyusb.c
host/class/cdc/usb_host_cdc_acm/test_app/main/usb_device.c
host/class/hid/usb_host_hid/test_app/main/hid_mock_device.c
host/class/msc/usb_host_msc/test_app/main/msc_device.c

esp_tinyusb will no longer initialize external PHY. If external PHY is required, it must be explicitly initialized by user and esp_tinyusb must be configured with `skip_phy_setup = true`
Closes https://github.com/espressif/esp-usb/issues/138

refactor(esp_tinyusb): Add an option to skip PHY setup

---

device/esp_tinyusb/tusb_msc_storage.c

---
**Why is this needed?**  
- **ESP32-S3 USB Mass Storage (MSC) implementation showed suboptimal performance** (slow file copy speed).  
- **Observed issues:**
- ⚠️ **SPI Flash write speed was severely limited** due to architectural constraints.  
- 📉 **SD card speeds varied significantly based on FIFO size**, but were still below expectations.  
- **Goal:** Optimize data transfer efficiency for both SPI Flash and SD cards.
---
This PR improves USB Mass Storage (MSC) performance by:
- ✅ **Caching `get_sector_size` and `get_sector_count`** to reduce redundant queries and improve efficiency.
- ✅ **Optimizing buffering logic:**
- **A single-buffer approach is used for all targets** (ESP32-S3, ESP32-P4, ESP32-S2)
- **Buffering significantly improves SD card write speed**, while SPI Flash …

fix(tusb_msc): Cache sector metrics, enable storage buffering

---

.github/workflows/build_and_run_test_app_usb.yml

Temporarily disable IDF Latest, to unlock CI until IDF-12980 is merged
IDF-12980
---

fix(ci): Temporarily disable IDF Latest in CI

---

device/esp_tinyusb/include/tusb_msc_storage.h
device/esp_tinyusb/tusb_msc_storage.c

Add Wear leveling sector size runtime check.
As the wear leveling sector size is only relevant to spiflash storage type (not SDMMC storage), the WL Sector size is checked during the `tinyusb_msc_storage_init_spiflash()`.
The `CONFIG_WL_SECTOR_SIZE` (being 4096 by default, but set to 512 using `sdkconfig.defaults` in [tusb_msc example](https://github.com/espressif/esp-idf/blob/master/examples/peripherals/usb/device/tusb_msc/sdkconfig.defaults#L10)) must be lower or equal to the `CONFIG_TINYUSB_MSC_BUFSIZE`.
- Reverting #157 
- Closes #159 
- Closes [TinyUSB MSC FAT format fails, flooding log with errors](https://github.com/espressif/esp-idf/issues/14566)
---

feat(tusb_msc): Add WL Sector runtime check during spiflash init

---

host/class/cdc/usb_host_cdc_acm/host_test/device_interaction/CMakeLists.txt
host/class/cdc/usb_host_cdc_acm/host_test/device_interaction/README.md
host/class/cdc/usb_host_cdc_acm/host_test/device_interaction/main/CMakeLists.txt
host/class/cdc/usb_host_cdc_acm/host_test/parsing_tests/CMakeLists.txt
host/class/hid/usb_host_hid/host_test/CMakeLists.txt
host/class/uac/usb_host_uac/host_test/CMakeLists.txt
host/class/uac/usb_host_uac/host_test/README.md
host/class/uac/usb_host_uac/host_test/main/CMakeLists.txt
host/class/uvc/usb_host_uvc/host_test/CMakeLists.txt
host/class/uvc/usb_host_uvc/host_test/README.md
host/class/uvc/usb_host_uvc/host_test/main/CMakeLists.txt

Updating path to USB Host CMock, as folder structure with USB mocks was updated.
Ready to merge, once the  is merged into esp-idf and master branches synced.
Changing USB Mock path from:
`"$ENV{IDF_PATH}/tools/mocks/usb/"`
to
`"$ENV{IDF_PATH}/tools/mocks/usb/usb_host_full_mock/usb/"`
- preceding:  
---

fix(usb_host): Update USB Host Cmock paths

---

.github/workflows/build_and_run_test_app_usb.yml

This MR enables the CI for IDF Latest back, after it was disabled due to an error in the IDF Latest. The master branches have synced, and the esp-idf [commit](https://github.com/espressif/esp-idf/commit/92ece05ac5384fddf572411ab73d957785f8ba14) which fixes the esp-usb CI is now present in the IDF Latest docker image.
To pass the esp-usb CI with the esp-idf latest.
---

fix(ci): Revert disabling IDF Latest in CI

---

device/esp_tinyusb/CHANGELOG.md
device/esp_tinyusb/idf_component.yml

- MSC: WL Sector runtime check during spiflash init (fix for build time error check)
Previous [release v1.7.3](https://components.espressif.com/components/espressif/esp_tinyusb/versions/1.7.3)  was yanked due to an error in #157, which was also a part of the release. This release fixes the error.
- https://github.com/espressif/esp-usb/pull/161

release(esp_tinyusb): v1.7.4

---

device/esp_tinyusb/CHANGELOG.md
device/esp_tinyusb/idf_component.yml

Adding support for IDF6 to esp_tinyusb to unblock its development.
There are no breaking changes planned at this time

feat(esp_tinyusb): Add support for IDF 6

---

device/esp_tinyusb/Kconfig
device/esp_tinyusb/tusb_msc_storage.c

As noted by @metainf in [issue #79](https://github.com/espressif/esp-usb/issues/79#issuecomment-2672324105), the current implementation of `f_mkfs()` uses a hardcoded value `FM_FAT` as the format type:  
https://github.com/espressif/esp-usb/blob/aef6153faad1cd957f789a702135155ce13aae30/device/esp_tinyusb/tusb_msc_storage.c#L228
Hardcoding `FM_FAT` restricts formatting to FAT12/16, which fails on volumes that require FAT32 or higher, such as an 8GB SDMMC. According to the [Keil File System 6.6 documentation](https://www.keil.com/pack/doc/mw6/FileSystem/html/fat_fs.html), the maximum volume sizes are:
- **FAT12**: up to 256MB  
- **FAT16**: up to 4GB  
- **FAT32**: up to 2TB  
Attempting to format an 8GB SDMMC using `FM_FAT` causes an error because it's above the FAT16 limit.
Make the …

feat(fat_format): add fat file format on kconfig to change MKFS_PARM format options (IEC-294)

---

device/esp_tinyusb/include/tusb_msc_storage.h
device/esp_tinyusb/tusb_msc_storage.c

This MR adds a possibility to define a user callback for device mount/unmount events.
Right now, the `tusb_msc_storage.c` automatically calls:
- `tinyusb_msc_storage_mount()` at `tud_umount_cb()`
- `tinyusb_msc_storage_unmount()` at `tud_mount_cb()`
User has no flexibility to do anything else upon the device mount/unmount.
This MR adds a flexibility to the user, to for example control an owership of the storage (eg, not to automatically unmount a storage when a USB device is plugged in)
Also cleaned conceptions between device mount/unmount and storage mount/unmount, not to confuse anyone when the code refers to device mount/unmount and when to storage mount/unmount.
Related to #78 
---

feat(tusb_msc): Add device mount/unmount callback

---

host/class/uvc/usb_host_uvc/CHANGELOG.md
host/class/uvc/usb_host_uvc/host_test/main/opening/test_opening.cpp
host/class/uvc/usb_host_uvc/host_test/main/parsing/test_parsing_anker_powerconf_c200.cpp
host/class/uvc/usb_host_uvc/host_test/main/parsing/test_parsing_canyon_cne_cwc2.cpp
host/class/uvc/usb_host_uvc/host_test/main/parsing/test_parsing_customer.cpp
host/class/uvc/usb_host_uvc/host_test/main/parsing/test_parsing_customer_dual.cpp
host/class/uvc/usb_host_uvc/host_test/main/parsing/test_parsing_elp_h264.cpp
host/class/uvc/usb_host_uvc/host_test/main/parsing/test_parsing_elp_h265.cpp
host/class/uvc/usb_host_uvc/host_test/main/parsing/test_parsing_helpers.hpp
host/class/uvc/usb_host_uvc/host_test/main/parsing/test_parsing_logitech_c270.cpp
host/class/uvc/usb_host_uvc/host_test/main/parsing/test_parsing_logitech_streamcam.cpp
host/class/uvc/usb_host_uvc/host_test/main/parsing/test_parsing_old.cpp
host/class/uvc/usb_host_uvc/host_test/main/parsing/test_parsing_trust_webcam.cpp
host/class/uvc/usb_host_uvc/host_test/main/parsing/test_parsing_tusb_dual.cpp
host/class/uvc/usb_host_uvc/include/esp_private/uvc_control.h
host/class/uvc/usb_host_uvc/include/esp_private/uvc_esp_video.h
host/class/uvc/usb_host_uvc/include/usb/uvc_host.h
host/class/uvc/usb_host_uvc/private_include/uvc_types_priv.h
host/class/uvc/usb_host_uvc/test_app/CMakeLists.txt
host/class/uvc/usb_host_uvc/test_app/README.md
host/class/uvc/usb_host_uvc/test_app/main/CMakeLists.txt
host/class/uvc/usb_host_uvc/test_app/main/idf_component.yml
host/class/uvc/usb_host_uvc/test_app/main/test_app_main.c
host/class/uvc/usb_host_uvc/test_app/main/test_uvc_host.c
host/class/uvc/usb_host_uvc/test_app/sdkconfig.defaults
host/class/uvc/usb_host_uvc/uvc_control.c
host/class/uvc/usb_host_uvc/uvc_descriptor_parsing.c
host/class/uvc/usb_host_uvc/uvc_host.c

Espressif's [esp_video](https://components.espressif.com/components/espressif/esp_video) component provides video pipeline and simulates V4L2 API. This MR updates UVC driver so it can be used in UVC video
* Added `uvc_host_stream_format_get()` and `uvc_host_buf_info_get()` functions that are needed for esp_video_uvc binding
* Added option to request default FPS and/or default format during format change
* Fixed minor bugs

UVC updates for esp_video

---

device/esp_tinyusb/include/tinyusb.h
device/esp_tinyusb/include/tinyusb_default_configs.h
device/esp_tinyusb/include/tusb_msc_storage.h
device/esp_tinyusb/test_apps/dconn_detection/main/test_dconn_detection.c
device/esp_tinyusb/test_apps/runtime_config/main/device_handling.c
device/esp_tinyusb/test_apps/runtime_config/main/device_handling.h
device/esp_tinyusb/test_apps/runtime_config/main/test_app_main.c
device/esp_tinyusb/test_apps/runtime_config/main/test_config.c
device/esp_tinyusb/test_apps/runtime_config/main/test_device.c
device/esp_tinyusb/test_apps/runtime_config/main/test_multitask_access.c
device/esp_tinyusb/test_apps/runtime_config/main/test_periph.c
device/esp_tinyusb/test_apps/runtime_config/main/test_task.c
device/esp_tinyusb/test_apps/runtime_config/main/test_task.h
device/esp_tinyusb/test_apps/teardown_device/main/test_teardown.c
device/esp_tinyusb/tinyusb.c
device/esp_tinyusb/tusb_msc_storage.c

User could specify the specific callback, that will be called with specific event:
- `TINYUSB_EVENT_ATTACHED`: Host enumerates the device and fulfill SetConfiguration() request on a device. 
- `TINYUSB_EVENT_DETACHED`: Device detaches from the Host. 
In the future, events list could be extended to: `SUSPEND`, `RESUME`, `SOF` etc.
- Prerequisites for https://github.com/espressif/esp-usb/pull/178
- https://github.com/espressif/esp-usb/pull/122
Testing is possible with the same tests.
---

feature(tinyusb): Added device events callback

---

.github/workflows/build_idf_examples.yml

Failing job https://github.com/espressif/esp-usb/actions/runs/15542561481/job/43756569788?pr=183

fix(ci): Use latest idf-component-manager from esp-idf docker image

---

device/esp_tinyusb/CHANGELOG.md
device/esp_tinyusb/tusb_msc_storage.c

The verification of the address value (the value, which is used for Wear Levelling above SPI Flash storage) is done when WRITE(10) command is coming, for both storages: SPI Flash and SD/MMC.
This verification is not relevant, when SD/MMC storage is used, as SD/MMC storage works with LBA directly. 
- Closes https://github.com/espressif/esp-idf/issues/16085
- Relates to https://github.com/espressif/esp-usb/pull/178
```
$ dd if=/dev/random of=/dev/sda bs=512 count=1 seek=124735487
$ dd if=/dev/sda iflag=direct bs=512 skip=124735487 count=1
```
1. After the change, the direct read/write of the last sector of the card with capacity of 64 GB completed successful and the data is valid. 
2. Without change, the direct read/write of the last sector of the uSD card with capacity of 64 GB completed …

fix(tinyusb_msc): Address calculation verification for SPI Flash

---

device/esp_tinyusb/CHANGELOG.md
device/esp_tinyusb/idf_component.yml

- MSC: Fixed the possibility to use SD/MMC storage with large capacity (more than 4 GB) (https://github.com/espressif/esp-usb/pull/186)
- Closes https://github.com/espressif/esp-idf/issues/16085

release(esp_tinyusb): v1.7.6

---

docs/device/migration-guides/v2/tinyusb_msc.md

Adding migration guide for Espressif's TinyUSB addition: MSC Storage.
Contain following topics: 
1. Do I need to migrate?
2. What to expect after migration?
3. List of changes
4. Compilation errors after the update and fix description
- Relates to https://github.com/espressif/esp-usb/pull/178
N/A
---

docs(tinyusb_msc): Added migration-guide for v2

---

device/esp_tinyusb/include/tinyusb_msc.h
device/esp_tinyusb/tinyusb_msc.c

Changing the flag name to make it common for every storage, not only LUN0.
N/A
N/A
---

refactor(tinyusb_msc): Changed the name of the auto mount flag

---

host/class/cdc/usb_host_ch34x_vcp/CHANGELOG.md
host/class/cdc/usb_host_ch34x_vcp/idf_component.yml
host/class/cdc/usb_host_ch34x_vcp/include/usb/vcp_ch34x.h
host/class/cdc/usb_host_ch34x_vcp/usb_host_ch34x_vcp.c
host/class/cdc/usb_host_cp210x_vcp/CHANGELOG.md
host/class/cdc/usb_host_cp210x_vcp/idf_component.yml
host/class/cdc/usb_host_cp210x_vcp/include/usb/vcp_cp210x.h
host/class/cdc/usb_host_cp210x_vcp/usb_host_cp210x_vcp.c

This PR adds support for PID autodetection of CP210x and CH34x devices. Feel free to close the PR, just a suggestion.
Tested only CP2102 detection in [esp-serial-flasher](https://github.com/espressif/esp-serial-flasher), while adding support to flash through USB-UART converters.
---

Add cp210x and ch34x PID autodetection (IEC-354)

---

device/esp_tinyusb/CHANGELOG.md
device/esp_tinyusb/include/tinyusb_msc.h
device/esp_tinyusb/test_apps/msc_storage/main/storage_common.c
device/esp_tinyusb/test_apps/msc_storage/main/storage_common.h
device/esp_tinyusb/test_apps/msc_storage/main/test_msc_storage.c
device/esp_tinyusb/tinyusb_msc.c

Now it is possible to format the storage with desirable flags (and file system type) either from the APP or from the USB Host.  
- Adding storage format.
- Removed the descriptors for TinyUSB configuration. Now the default config is used. 
- Closes [IEC-319](https://jira.espressif.com:8443/browse/IEC-319)
Additional test cases were added to `msc_storage` test application: 
- `MSC: format storage SPI Flash, mounted to APP`
- `MSC: format storage SPI Flash, mounted to USB`
- `MSC: format storage SD/MMC, mounted to APP`
---

feature(tinyusb_msc): Added storage format logic

---

device/esp_tinyusb/README.md
device/esp_tinyusb/idf_component.yml

1. Fixed link to migration guides v2.0.0
2. Added supported targets in `idf_component.yml `
- https://github.com/espressif/esp-usb/pull/201
---

fix(esp_tinyusb): Migration guides link in README.md

---

.build-test-rules.yml

This MR re-enables Linux host test run in CI. 
Combination of 2 following settings disabled host tests run in CI by accident:
`.build-test-rules.yml`
```yml
host/class/cdc/usb_host_cdc_acm/host_test:
enable:
- if: IDF_TARGET in ["linux"] and (IDF_VERSION_MAJOR >= 5 and IDF_VERSION_MINOR >= 5)
reason: USB mocks are run only for the latest version of IDF
```
`.build_and_run_host_test.yml`
```yml
jobs:
...
matrix:
idf_ver: ["latest"]
```
Where `DF_VERSION_MAJOR >= 5 and IDF_VERSION_MINOR >= 5` does not satisfy for `IDF Latest` being `IDF 6.0`
<details>
<summary> USB Host test CI log </summary>
```bash
Successfully installed idf-build-apps-2.4.3 iniconfig-2.1.0 pluggy-1.6.0 pytest-8.4.1
Using config file: /__w/esp-usb/esp-usb/.idf_build_apps.toml
Using config file: …
```

fix(ci): Re-enable linux host tests for IDF 6.0

---

device/esp_tinyusb/CHANGELOG.md
device/esp_tinyusb/include/tinyusb_net.h
device/esp_tinyusb/test_apps/ncm/CMakeLists.txt
device/esp_tinyusb/test_apps/ncm/main/CMakeLists.txt
device/esp_tinyusb/test_apps/ncm/main/device_common.c
device/esp_tinyusb/test_apps/ncm/main/device_common.h
device/esp_tinyusb/test_apps/ncm/main/idf_component.yml
device/esp_tinyusb/test_apps/ncm/main/test_app_main.c
device/esp_tinyusb/test_apps/ncm/main/test_ncm.c
device/esp_tinyusb/test_apps/ncm/sdkconfig.defaults
device/esp_tinyusb/tinyusb_net.c
docs/device/migration-guides/v2/tinyusb_ncm.md

Added `tinyusb_net_deinit()` public API call.
Based on the review comment: https://github.com/espressif/esp-usb/pull/201#discussion_r2266941849
- Closes IEC-352
- Added test case to init and deinit TinyUSB NCM driver and verify memory leakage.
---

refactor(tinyusb_net): Added deinit API

---

.github/workflows/build_idf_examples.yml
device/esp_tinyusb/CHANGELOG.md
device/esp_tinyusb/CMakeLists.txt

Removed usb component dependency for esp-idf v6 and greater. 
For esp-idf major version less than 6, the private requirement of usb component (from esp-idf) is being set. 
- Cherry-picked https://github.com/espressif/esp-usb/pull/231
- Relates to IDF-14022
N/A
---

fix(esp_tinyusb): Remove usb component private requirement for idf v6 (v1)

---

device/esp_tinyusb/CMakeLists.txt

Applying the logic from https://github.com/espressif/esp-usb/pull/243 for v2.0.0 release. 
N/A
N/A
---

fix(esp_tinyusb): Remove usb component private requirement for idf v6 (v2)

---

.github/ci/.idf-build-examples-rules.yml
.github/ci/.idf_build_examples_config.toml
.github/ci/override_managed_component.py
.github/workflows/build_and_run_test_app_usb.yml
.github/workflows/build_idf_examples.yml
host/usb/CMakeLists.txt
host/usb/idf_component.yml
host/usb/src/hcd_dwc.c
host/usb/src/usb_host.c

This MR adds support for usb component overriding.
In case users want to use the managed `usb` component  from `esp-usb` instead of the native `usb` component present in `esp-idf v5.x` service release. 
- USB component overriding is only possible in IDF Service releases: `IDF 5.4 and IDF 5.5`
- Run esp-idf host examples in CI with the current usb component
- `build_idf_examples.yml` only built `USB Device` examples from `esp-idf` with overriden version of `esp_tinyusb` component
- the workflow is extended to run `USB Host` examples with the overridden `usb` component from `esp-usb/host/usb/`
- USB Component: esp-idf USB located in `esp-idf/components/usb`
- USB Mocks: esp-idf USB Mocks in `esp-idf/tools/mocks/usb`
| IDF    | Class Tests        | USB Component tests| idf examples (host)| …

feat(usb_host): USB Component overriding in IDF service releases

---

device/esp_tinyusb/tinyusb_msc.c
host/class/msc/usb_host_msc/src/msc_host_vfs.c

The original `esp_vfs_fat_register` function prototype is getting changed for `esp_vfs_fat_register_cfg` in IDF v6.0 (breaking change), so `esp_vfs_fat_register_cfg` and `esp_vfs_fat_register` will be the same. `esp_vfs_fat_register_cfg` function will stay as an alias for `esp_vfs_fat_register` for now.
`esp_vfs_fat_register_cfg` is used everywhere in the IDF right now.
---

refactor: Use esp_vfs_fat_register_cfg instead of esp_vfs_fat_register (IEC-381)

---

.github/workflows/build_and_run_test_app_usb.yml
host/usb/test/target_test/hcd/pytest_usb_hcd.py
host/usb/test/target_test/usb_host/pytest_usb_host.py

New `usb_host_flash_disk` runners were added to the `esp-usb` ci setup, allowing us to run USB Component target tests.
- BrnoRPIG015 `esp32p4` `usb_host_flash_disk`
- BrnoRPIG017 `esp32s2` `usb_host_flash_disk`
- closes IDF-14057: Add new target runners to esp-usb CI workflow
---

feat(ci): Run target tests on usb_host_flash_disk runners

---

device/esp_tinyusb/test_apps/msc_storage/main/device_common.c

In some cases, `tud_mount_cb()` is not called within 5000 ms. (For example: https://github.com/espressif/esp-usb/actions/runs/17772807754/job/50515316959?pr=255#step:7:923)
As the reason is unknown, the warning debug output was added if the first iteration of waiting ended with negative result. 
Changed the logic to the two iterations of device connection callback waiting: 
1. Wait for 5000 ms
2. If yes, goto 6.
3. If no, wait another 5000 ms
4. If yes, goto 6.
5. If no - abort the test with error
6. Proceed the test
- Relates to https://github.com/espressif/esp-usb/pull/258
- Relates to https://github.com/espressif/esp-usb/pull/255
---

fix(test_apps): Added two attempts of waiting for tud_connect_cb()

---

device/esp_tinyusb/CHANGELOG.md
device/esp_tinyusb/Kconfig
device/esp_tinyusb/idf_component.yml

This PR enables **ESP32-H4** as a supported target in `esp-usb` with FS-appropriate defaults. It pairs with the TinyUSB PR that adds H4 support to the DCD path.
- **Kconfig**
- Treat H4 like S2/S3 (Full-Speed):
`TINYUSB_MSC_BUFSIZE` default **512**, range **64..8192**
(`IDF_TARGET_ESP32H4` added alongside S2/S3)
- **Component manifest**
- `idf_component.yml`: add `esp32h4` to `targets`
_No behavior change for other targets;
- **TinyUSB PR (Espressif fork):** Add ESP32-H4 support  
espressif/tinyusb PR #<59> (branch `feat/tinyusb_esp32h4_support`)
> esp-usb builds/tests for H4 should be run after (or with) the TinyUSB H4 PR so the DCD is available.
- H4 is a FS-only SoC similar to S2/S3 for USB OTG usage. Reusing the same defaults keeps memory usage modest while providing solid MSC/CDC …

feat(h4): Add ESP32-H4 support in esp-usb

---

device/esp_tinyusb/tinyusb_msc.c

[Storage / FATFS] Function `esp_vfs_fat_register_cfg` has been deprecated and will be removed in the future.
- Relates [!41953](https://gitlab.espressif.cn:6688/espressif/esp-idf/-/merge_requests/41953)
- Unlocks esp-idf v6.0 CI
N/A
---

refactor(tinyusb_msc): Removed deprecated esp_vfs_fat_register_cfg API call (esp-idf v6.0)

---

device/esp_tinyusb/CHANGELOG.md
device/esp_tinyusb/idf_component.yml

- esp_tinyusb: Added ESP32H4 support
- esp_tinyusb: Fixed an assertion failure on the GetOtherSpeedDescriptor() request for ESP32P4 when the OTG1.1 port is used
- MSC: Added dynamic member and storage operation multitask protection
- MSC: Used `esp_vfs_fat_register_cfg` function prototype for esp-idf v5.3 and higher
- https://github.com/espressif/esp-usb/pull/213
- https://github.com/espressif/esp-usb/pull/258
- https://github.com/espressif/esp-usb/pull/257
- https://github.com/espressif/esp-usb/pull/250
- https://github.com/espressif/esp-usb/pull/268
---

release(esp_tinyusb): v2.0.1

---

host/class/cdc/esp_modem_usb_dte/esp_modem_usb.cpp
host/class/cdc/usb_host_cdc_acm/test_app/main/test_cdc_acm_host.c
host/class/hid/usb_host_hid/test_app/main/test_hid_basic.c
host/class/msc/usb_host_msc/test_app/main/test_msc.c
host/class/uac/usb_host_uac/test_app/main/test_host_uac.c
host/class/uvc/usb_host_uvc/examples/basic_uvc_stream/main/basic_uvc_stream.c
host/class/uvc/usb_host_uvc/examples/camera_display/main/camera_display.c
host/class/uvc/usb_host_uvc/test_app/main/test_uvc_host.c
host/usb/test/target_test/common/hcd_common.c
host/usb/test/target_test/usb_host/main/test_app_main.c

This initialization code is often reused or copy-pasted by users. To prevent situations when the user's system runs out of priority 1 interrupts, we can allow priorities 1 to 3. This results in easier to port code.
Related to https://github.com/espressif/esp-idf/issues/17525

fix: Use ESP_INTR_FLAG_LOWMED for interrupt priority

---

host/class/cdc/usb_host_cdc_acm/test_app/main/idf_component.yml
host/class/msc/usb_host_msc/test_app/main/msc_device.c

Temporarily disable esp_modem_usb_dte builds until esp_modem is updated for IDF6.0

ci: Temporarily disable esp_modem_usb_dte to fix build issues

---

host/usb/README.md
host/usb/idf_component.yml

Update host/usb/README.md with esp-idf compatibility paragraph.

docs(host): Add note about esp-idf compatibility
